<S> = <CREATE> <BLANK+> <TABLE> <BLANK+> TABLE_NAME <BLANK*> <LEFTP> COLUMN_LINE* LAST_COLUMN_LINE
COLUMN_LINE = <BLANK*> COLUMN <SPACE+> COLUMN_TYPE <BLANK*> OTHER* <BLANK*> <ENDOFCOLUMN> <BLANK*>
LAST_COLUMN_LINE = <BLANK*> COLUMN <SPACE+> COLUMN_TYPE <BLANK*> OTHER* <BLANK*> <RIGHTP> <BLANK*>

SPACE = #'\s|\r\n|\n'
BLANK = #"(\s+|\s*--.*(\r\n|\n)*|\r\n|\n)"
CREATE = #'(?i)create'
TABLE = #'(?i)table'
TABLE_NAME = #"[a-zA-Z0-9-_]+"
OTHER = #'[^,]'
COLUMN = #'[a-zA-Z]\S*'
COLUMN_TYPE = COLUMN_TYPE_OTHER
<COLUMN_TYPE_OTHER> = #'PRIMARY\s+KEY|[a-zA-Z0-9]+(\([0-9]+\))?\S*'
COLUMN_TYPE_PRIMARY = 'PRIMARY KEY'
ENDOFCOLUMN = ','
LEFTP = '('
RIGHTP = ')'
NEWLINE = '\n' | '\r\n'
